version: "3"
services:
  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/usr/share/caddy/index.html
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  v2ray:
    image: v2fly/v2fly-core
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    command: ["run", "-c", "/etc/v2ray/config.json"]
