version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8020:8020"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
